### ISSUE TITLE
Allow Gradle sync to complete without configuring OpenAPI-kt

### ISSUE THREAD

**Issue by martinbonnin** [nomisRev/OpenAPI-kt#88]
Because of Gradle borked way of handling classpaths, a Gradle sync is necessary in order to have autocomplete in `build.gradle.kts` files.

A simple project like so:

```kotlin
plugins {
  id("org.jetbrains.kotlin.jvm")
  id("io.github.nomisrev.openapi-kt-plugin")
}

// No openApiConfig here
```

fails Gradle sync with:

```
Caused by: java.lang.IllegalArgumentException: No OpenAPI Config found
	at io.github.nomisrev.openapi.plugin.GenerateClientTask.sampleAction(GenerateClientTask.kt:34)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

It'd be nice if the Gradle sync could go through so that we could type the config using IDE support.

**Comment by nomisRev** [comment]
I rewrote to Gratatouille I think this is now fixed. Please re-open or new issue when something else is broken. There is still some work to do on the Gradle setup, and I'd love to support Kotlin Toolchain asap. See #243
